name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set Kotlin Toolchain shared cache directory
        run: echo "KOTLIN_SHARED_CACHE_DIR=$HOME/.kotlin-shared-cache" >> $GITHUB_ENV

      - name: Cache Kotlin Toolchain
        uses: actions/cache@v6
        with:
          path: ${{ env.KOTLIN_SHARED_CACHE_DIR }}
          key: kotlin-toolchain-${{ runner.os }}-${{ hashFiles('**/module.yaml', 'libs.versions.toml') }}
          restore-keys: |
            kotlin-toolchain-${{ runner.os }}-

      - name: Build
        run: ./kotlin build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts
          path: build/tasks/_menv_linkMingwX64Debug/
