name: Shared Build
on:
  workflow_call:
    inputs:
      release-build:
        description: Whether to perform a release build
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set Kotlin Toolchain shared cache directory
        run: echo "KOTLIN_SHARED_CACHE_DIR=$HOME/.kotlin-shared-cache" >> $GITHUB_ENV

      - name: Cache Kotlin Toolchain shared
        uses: actions/cache@v6
        with:
          path: ${{ env.KOTLIN_SHARED_CACHE_DIR }}
          key: kotlin-toolchain-shared-${{ runner.os }}-${{ hashFiles('**/module.yaml', 'libs.versions.toml') }}
          restore-keys: |
            kotlin-toolchain-shared-${{ runner.os }}-

      - name: Cache Konan
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: konan-${{ runner.os }}-${{ hashFiles('**/module.yaml', 'libs.versions.toml') }}
          restore-keys: |
            konan-${{ runner.os }}-

      - name: Grant execute permission for kotlin
        run: chmod +x kotlin

      - name: Build
        # language=bash
        run: |
          if [ "${{ inputs.release-build }}" = "true" ]; then
              ./kotlin build --variant=release
          else
              ./kotlin build
          fi

      - name: Upload build artifacts
        if: ${{ !inputs.release-build }}
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts
          path: build/tasks/_menv_linkMingwX64Debug/

      - name: Upload release artifacts
        if: ${{ inputs.release-build }}
        uses: actions/upload-artifact@v7
        with:
          name: release-artifacts
          path: build/tasks/_menv_linkMingwX64Release/
          if-no-files-found: error
